# Generated by Django 2.1.7 on 2024-10-16 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0011_auto_20240822_1434'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Бодит үйл явдал болсон огноо')),
                ('store_no', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Store number must be a 5-digit number')], verbose_name='Үйл явдал болсон дэлгүүрийн дугаар')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disp_desc', models.TextField(verbose_name='Болсон хэргийн талаар дэлгэрэнгүй мэдээлэл')),
                ('disp_cat', models.CharField(max_length=50, verbose_name='Хэргийн төрөл')),
                ('dmg_amt', models.FloatField(default=0, verbose_name='Хохирлын хэмжээ /мөнгөн дүн/')),
                ('dmg_uom', models.CharField(max_length=255, verbose_name='Хохирлын хэмжигдэхүүн')),
                ('disp_status', models.BooleanField(blank=True, null=True, verbose_name='Хэргийн төлөв')),
                ('disp_progress', models.CharField(blank=True, max_length=500, null=True, verbose_name='Хэргийн явц')),
                ('disp_result', models.BooleanField(blank=True, null=True, verbose_name='Хэрэг шийдэгдсэн эсэх')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Хэрэг шийдэгдсэн өдөр')),
                ('supp_link', models.URLField(blank=True, null=True, verbose_name='Холбогдох баримт бичгийн холбоос')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('disp_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ActionOwner')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'DisputeTable',
                'db_table': 'dispute',
            },
        ),
    ]
