# Generated by Django 2.1.7 on 2024-10-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type_name', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('employee_code', models.CharField(max_length=50)),
                ('origin_name', models.CharField(max_length=255)),
                ('urag', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('state_reg_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('employee_phone', models.CharField(max_length=50)),
                ('post_address', models.EmailField(max_length=254)),
                ('education_level', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=50)),
                ('no_of_family_members', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('insured_type_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('mobile', models.CharField(max_length=50)),
                ('work_name', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='veritech_api.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='veritech_api.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='veritech_api.Employee'),
        ),
        migrations.AddField(
            model_name='address',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='veritech_api.Employee'),
        ),
    ]
