# Generated by Django 2.1.7 on 2024-10-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0002_auto_20241010_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(blank=True, max_length=255, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=255, null=True)),
                ('positionname', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipname', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('workname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('employeecode', models.CharField(blank=True, max_length=255, null=True)),
                ('originname', models.CharField(blank=True, max_length=255, null=True)),
                ('urag', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('stateregnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('employeephone', models.CharField(blank=True, max_length=255, null=True)),
                ('postaddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('educationlevel', models.CharField(blank=True, max_length=255, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('nooffamilymember', models.IntegerField(blank=True, null=True)),
                ('noofchildren', models.IntegerField(blank=True, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=255, null=True)),
                ('positionname', models.CharField(blank=True, max_length=255, null=True)),
                ('insuredtypename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='employee',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_type_name',
            new_name='addresstypename',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city_name',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='district_name',
            new_name='districtname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_name',
            new_name='streetname',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_account_number',
            new_name='bankaccountnumber',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='bankname',
        ),
        migrations.RemoveField(
            model_name='address',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='employee',
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.AddField(
            model_name='family',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veritech_api.General'),
        ),
        migrations.AddField(
            model_name='experience',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veritech_api.General'),
        ),
        migrations.AddField(
            model_name='address',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veritech_api.General'),
        ),
        migrations.AddField(
            model_name='bank',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veritech_api.General'),
        ),
    ]
