# Generated by Django 2.1.7 on 2024-10-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0003_auto_20241010_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='employeeid',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
