# Generated by Django 2.1.7 on 2024-10-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0006_auto_20241016_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Attitude',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
