# Generated by Django 2.1.7 on 2024-02-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_planning', '0002_auto_20240208_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplanning',
            name='propose',
            field=models.TextField(blank=True, null=True, verbose_name='Suggestions for improvement'),
        ),
    ]
