# Generated by Django 2.1.7 on 2024-02-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_planning', '0003_auto_20240208_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeplanning',
            name='addr1_prov',
        ),
        migrations.RemoveField(
            model_name='storeplanning',
            name='addr2_dist',
        ),
        migrations.RemoveField(
            model_name='storeplanning',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storeplanning',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='StorePlanning',
        ),
    ]
