# Generated by Django 2.1.7 on 2024-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=5, null=True, verbose_name='Салбарын дугаар')),
                ('str_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Салбарын нэр')),
                ('str_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Албан ёсны хаяг')),
                ('lesser1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Түрээслүүлэгч 1 ')),
                ('lesser2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Түрээслүүлэгч 2')),
                ('phone_number1', models.IntegerField(blank=True, default=0, null=True, verbose_name='Холбоо барих утас 1')),
                ('phone_number2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Холбоо барих утас 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='И-майл хаяг')),
                ('area_size', models.IntegerField(blank=True, null=True, verbose_name='Талбайн нийт хэмжээ м.кв')),
                ('cont_type', models.BooleanField(blank=True, null=True, verbose_name='Гэрээний төрөл')),
                ('cntr_num1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Гэрээний дугаар 1')),
                ('cntr_num2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Гэрээний дугаар 2')),
                ('st_dt', models.DateField(blank=True, null=True, verbose_name='Гэрээ эхлэх хугацаа')),
                ('ed_dt', models.DateField(blank=True, null=True, verbose_name='Дуусах хугацаа ')),
                ('ext_ed_dt', models.DateField(blank=True, null=True, verbose_name='Сунгагдсан хугацаа')),
                ('hand_over_dt', models.DateField(blank=True, null=True, verbose_name='Талбай хүлээлцсэн актын өдөр')),
                ('rent_mo_fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='Түрээсийн төлбөр ')),
                ('rent_mo_fee_annex1', models.IntegerField(blank=True, default=0, null=True, verbose_name='Түрээсийн төлбөр 1')),
                ('rent_mo_fee_annex2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Түрээсийн төлбөр 2')),
                ('deposit_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Барьцаа төлбөр')),
                ('association_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='СӨХ гэрээний дугаар ')),
                ('association_fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='СӨХ-ийн төлбөр')),
                ('manage_cnt_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Менежемент гэрээний дугаар')),
                ('manage_fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='Менежментийн төлбөр')),
                ('exp_inc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Гэрээнд орсон зардал')),
                ('orther_cnt', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бусад орлого болон зардлын гэрээ')),
                ('stora_yn', models.BooleanField(blank=True, null=True, verbose_name='Stora box')),
                ('stora_fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stora box түрээсийн төлбөр')),
                ('atm_yn', models.BooleanField(blank=True, null=True, verbose_name='ATM')),
                ('atm_fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='ATM түрээсийн төлбөр')),
                ('sublet_yn', models.BooleanField(blank=True, null=True, verbose_name='Дамжуулан түрээслэх боломжтой эсэх')),
                ('sublet1_cnt_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='1 Дамжуулан түрээсийн гэрээний дугаар')),
                ('sublet1_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='1 Дамжуулан түрээсийн талбай хэмжээ')),
                ('sublet1_rent', models.IntegerField(blank=True, default=0, null=True, verbose_name='1 Дамжуулан түрээсийн үнэ ')),
                ('sublet1_deposit', models.IntegerField(blank=True, default=0, null=True, verbose_name='1 Дамжуулан түрээсийн барьцаа төлбөр')),
                ('sublet2_cnt_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='2 Дамжуулан түрээсийн гэрээний дугаар')),
                ('sublet2_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='2 Дамжуулан түрээсийн талбай хэмжээ')),
                ('sublet2_rent', models.IntegerField(blank=True, default=0, null=True, verbose_name='2 Дамжуулан түрээсийн үнэ')),
                ('sublet2_deposit', models.IntegerField(blank=True, default=0, null=True, verbose_name='2 Дамжуулан түрээсийн барьцаа төлбөр')),
                ('letter', models.CharField(blank=True, max_length=30, null=True, verbose_name='Албан бичиг')),
                ('notice', models.CharField(blank=True, max_length=200, null=True, verbose_name='Өргөдөл')),
                ('other_cnt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Бусад гэрээ')),
                ('franchise_yn', models.BooleanField(blank=True, null=True, verbose_name='Франчайз санал болгох заалттай')),
                ('fr_rent_yn', models.BooleanField(blank=True, null=True, verbose_name='Дамжуулан түрээсийн заалт')),
                ('dedication', models.BooleanField(blank=True, null=True, verbose_name='Үл хөдлөх хөрөнгийн зориулалт')),
                ('notariat_yn', models.BooleanField(blank=True, null=True, verbose_name='Нотариат')),
                ('real_estate_yn', models.BooleanField(blank=True, null=True, verbose_name='ҮХХ-н гэрчилгээтэй эсэх')),
                ('special_terms', models.CharField(blank=True, max_length=30, null=True, verbose_name='Гэрээний онцгой нөхцөл')),
                ('cont_resp_term', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гэрээний хариуцлагын заалт')),
                ('cont_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гэрээний холбоос')),
            ],
            options={
                'verbose_name': 'Rent',
                'db_table': 'str_rent',
            },
        ),
    ]
