# Generated by Django 2.1.7 on 2024-03-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='lesser1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Түрээслүүлэгч 1'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_trainer.StoreTrainer', verbose_name='Store ID'),
        ),
    ]
