# Generated by Django 2.1.7 on 2024-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20240325_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='strrent',
            name='cntr_num3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Гэрээний дугаар 3'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='lesser3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Түрээслүүлэгч 3'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='phone_number3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Холбоо барих утас 2'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='rent_mo_fee_annex3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Түрээсийн төлбөр 3'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='sublet3_cnt_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='3 Дамжуулан түрээсийн гэрээний дугаар'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='sublet3_deposit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='3 Дамжуулан түрээсийн барьцаа төлбөр'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='sublet3_rent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='3 Дамжуулан түрээсийн үнэ'),
        ),
        migrations.AddField(
            model_name='strrent',
            name='sublet3_size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='3 Дамжуулан түрээсийн талбай хэмжээ'),
        ),
    ]
