# Generated by Django 2.1.7 on 2024-03-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20240327_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strrent',
            old_name='orther_cnt',
            new_name='other_cnt',
        ),
    ]
