# Generated by Django 2.1.7 on 2024-03-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20240327_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='area_size',
            field=models.IntegerField(null=True, verbose_name='Талбайн нийт хэмжээ м.кв'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='association_fee',
            field=models.IntegerField(default=0, null=True, verbose_name='СӨХ-ийн төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='association_no',
            field=models.CharField(max_length=30, null=True, verbose_name='СӨХ гэрээний дугаар '),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='atm_fee',
            field=models.IntegerField(default=0, null=True, verbose_name='ATM түрээсийн төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='atm_yn',
            field=models.BooleanField(null=True, verbose_name='ATM'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='cntr_num1',
            field=models.CharField(max_length=30, null=True, verbose_name='Гэрээний дугаар 1'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='cntr_num2',
            field=models.CharField(max_length=30, null=True, verbose_name='Гэрээний дугаар 2'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='cont_link',
            field=models.CharField(max_length=50, null=True, verbose_name='Гэрээний холбоос'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='cont_resp_term',
            field=models.CharField(max_length=50, null=True, verbose_name='Гэрээний хариуцлагын заалт'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='cont_type',
            field=models.BooleanField(null=True, verbose_name='Гэрээний төрөл'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='dedication',
            field=models.BooleanField(null=True, verbose_name='Үл хөдлөх хөрөнгийн зориулалт'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='deposit_amount',
            field=models.IntegerField(default=0, null=True, verbose_name='Барьцаа төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='ed_dt',
            field=models.DateField(null=True, verbose_name='Дуусах хугацаа '),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='И-майл хаяг'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='exp_inc',
            field=models.CharField(max_length=30, null=True, verbose_name='Гэрээнд орсон зардал'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='ext_ed_dt',
            field=models.DateField(null=True, verbose_name='Сунгагдсан хугацаа'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='fr_rent_yn',
            field=models.BooleanField(null=True, verbose_name='Дамжуулан түрээсийн заалт'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='franchise_yn',
            field=models.BooleanField(null=True, verbose_name='Франчайз санал болгох заалттай'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='hand_over_dt',
            field=models.DateField(null=True, verbose_name='Талбай хүлээлцсэн актын өдөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='lesser1',
            field=models.CharField(max_length=100, null=True, verbose_name='Түрээслүүлэгч 1'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='lesser2',
            field=models.CharField(max_length=100, null=True, verbose_name='Түрээслүүлэгч 2'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='manage_cnt_no',
            field=models.CharField(max_length=30, null=True, verbose_name='Менежемент гэрээний дугаар'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='manage_fee',
            field=models.IntegerField(default=0, null=True, verbose_name='Менежментийн төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='notariat_yn',
            field=models.BooleanField(null=True, verbose_name='Нотариат'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='other_cnt',
            field=models.CharField(max_length=30, null=True, verbose_name='Бусад орлого болон зардлын гэрээ'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='phone_number1',
            field=models.IntegerField(default=0, null=True, verbose_name='Холбоо барих утас 1'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='phone_number2',
            field=models.IntegerField(default=0, null=True, verbose_name='Холбоо барих утас 2'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='phone_number3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Холбоо барих утас 3'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='real_estate_yn',
            field=models.BooleanField(null=True, verbose_name='ҮХХ-н гэрчилгээтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='rent_mo_fee',
            field=models.IntegerField(default=0, null=True, verbose_name='Түрээсийн төлбөр '),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='rent_mo_fee_annex1',
            field=models.IntegerField(default=0, null=True, verbose_name='Түрээсийн төлбөр 1'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='st_dt',
            field=models.DateField(null=True, verbose_name='Гэрээ эхлэх хугацаа'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='stora_fee',
            field=models.IntegerField(default=0, null=True, verbose_name='Stora box түрээсийн төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='stora_yn',
            field=models.BooleanField(null=True, verbose_name='Stora box'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_trainer.StoreTrainer', verbose_name='Store ID'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='str_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Албан ёсны хаяг'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='str_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Салбарын нэр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_cnt_no',
            field=models.CharField(max_length=30, null=True, verbose_name='1 Дамжуулан түрээсийн гэрээний дугаар'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_deposit',
            field=models.IntegerField(default=0, null=True, verbose_name='1 Дамжуулан түрээсийн барьцаа төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_rent',
            field=models.IntegerField(default=0, null=True, verbose_name='1 Дамжуулан түрээсийн үнэ '),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_size',
            field=models.IntegerField(default=0, null=True, verbose_name='1 Дамжуулан түрээсийн талбай хэмжээ'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet_yn',
            field=models.BooleanField(null=True, verbose_name='Дамжуулан түрээслэх боломжтой эсэх'),
        ),
    ]
