# Generated by Django 2.1.7 on 2024-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20240328_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='cntr_num2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Гэрээний дугаар 2'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='ext_ed_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Сунгагдсан хугацаа'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='lesser2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Түрээслүүлэгч 2'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='other_cnt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бусад орлого болон зардлын гэрээ'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='phone_number2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Холбоо барих утас 2'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='rent_mo_fee_annex1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Түрээсийн төлбөр 1'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_cnt_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1 Дамжуулан түрээсийн гэрээний дугаар'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_deposit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='1 Дамжуулан түрээсийн барьцаа төлбөр'),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_rent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='1 Дамжуулан түрээсийн үнэ '),
        ),
        migrations.AlterField(
            model_name='strrent',
            name='sublet1_size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='1 Дамжуулан түрээсийн талбай хэмжээ'),
        ),
    ]
