# Generated by Django 2.1.7 on 2024-04-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20240401_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='ext_ed_dt',
            field=models.DateField(null=True, verbose_name='Сунгагдсан хугацаа'),
        ),
    ]
