# Generated by Django 2.1.7 on 2024-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20240401_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='cont_type',
            field=models.CharField(blank=True, choices=[('basic', 'Үндсэн'), ('renewal', 'Сунгалт'), ('additional', 'Нэмэлт')], max_length=10, null=True, verbose_name='Contract Type'),
        ),
    ]
