# Generated by Django 2.1.7 on 2024-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_auto_20240404_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='dedication',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Үл хөдлөх хөрөнгийн зориулалт'),
        ),
    ]
