# Generated by Django 2.1.7 on 2024-06-27 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_auto_20240627_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Store number must be a 5-digit number')]),
        ),
    ]
