# Generated by Django 2.1.7 on 2024-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_auto_20240626_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecompetitors',
            name='comp_schedule_time',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Өрсөлдөгчийн цагийн хуваарь'),
        ),
    ]
