# Generated by Django 2.1.7 on 2024-06-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_auto_20240627_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimcomptype',
            old_name='comp_type',
            new_name='comp_tp',
        ),
    ]
