# Generated by Django 2.1.7 on 2024-07-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0004_auto_20240627_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecompetitors',
            name='comp_cluster',
        ),
        migrations.RemoveField(
            model_name='storecompetitors',
            name='comp_type',
        ),
        migrations.DeleteModel(
            name='DimCluster',
        ),
        migrations.DeleteModel(
            name='DimCompType',
        ),
        migrations.DeleteModel(
            name='StoreCompetitors',
        ),
    ]
