# Generated by Django 2.1.7 on 2024-07-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0005_auto_20240701_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCluster',
            fields=[
                ('common_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Common Code')),
                ('common_code_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Common Code Name')),
            ],
            options={
                'verbose_name': 'Dim Cluster',
                'db_table': 'dim_cluster',
            },
        ),
        migrations.CreateModel(
            name='DimCompType',
            fields=[
                ('comp_tp', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Competitor Type')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Competitor Type',
                'db_table': 'dim_comp_type',
            },
        ),
        migrations.CreateModel(
            name='StoreCompetitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=5, null=True, verbose_name='Дэлгүүрийн дугаар')),
                ('comp_yn', models.BooleanField(blank=True, null=True, verbose_name='Урсгалд нөлөөлөх өрсөлдөгч байгаа эсэх')),
                ('comp_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Өрсөлдөгчийн нэр')),
                ('comp_range_meter', models.FloatField(blank=True, default=0, null=True, verbose_name='Өрсөлдөгчийн манай дэлгүүрээс ойролцоогоор хэдэн метерт')),
                ('comp_open_dt', models.DateField(blank=True, null=True, verbose_name='Өрсөлдөгч хэзээ нээсэн')),
                ('comp_status', models.BooleanField(blank=True, null=True, verbose_name='Өрсөлдөгч хэвийн ажиллаж байгаа')),
                ('comp_close_dt', models.DateField(blank=True, null=True, verbose_name='Өрсөлдөгч хаасан бол хэзээ хаасан')),
                ('comp_schedule_tp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Өрсөлдөгчийн цагийн хуваарийн төрөл')),
                ('comp_schedule_time', models.CharField(blank=True, max_length=11, null=True, verbose_name='Өрсөлдөгчийн цагийн хуваарь')),
                ('comp_size', models.FloatField(blank=True, default=0, null=True, verbose_name='Өрсөлдөгчийн талбай')),
                ('comp_shelf_qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='Өрсөлдөгчийн лангууны тоо')),
                ('comp_alcohol', models.BooleanField(blank=True, null=True, verbose_name='Өрсөлдөгч архи зардаг эсэх')),
                ('comp_tabacco', models.BooleanField(blank=True, null=True, verbose_name='Өрсөлдөгч тамхи зардаг эсэх')),
                ('comp_delivery', models.BooleanField(blank=True, null=True, verbose_name='Өрсөлдөгч хүргэлттэй эсэх')),
                ('comp_pros', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Өрсөлдөгчийн давуу тал')),
                ('comp_long', models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Өрсөлдөгчийн Уртраг')),
                ('comp_latt', models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Өрсөлдөгчийн Өргөрөг')),
                ('comp_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitors.DimCluster')),
                ('comp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitors.DimCompType')),
            ],
            options={
                'verbose_name': 'Store Competitors',
                'db_table': 'store_competitors',
            },
        ),
    ]
