# Generated by Django 2.1.7 on 2024-07-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0006_dimcluster_dimcomptype_storecompetitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecompetitors',
            name='store_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Салбарын нэр'),
        ),
    ]
