# Generated by Django 2.1.7 on 2024-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0007_storecompetitors_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecompetitors',
            name='comp_close_dt',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Өрсөлдөгч хаасан бол хэзээ хаасан'),
        ),
        migrations.AlterField(
            model_name='storecompetitors',
            name='comp_open_dt',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Өрсөлдөгч хэзээ нээсэн'),
        ),
    ]
