# Generated by Django 2.1.7 on 2024-02-07 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Store id')),
                ('team_mgr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Team manager name')),
                ('sc_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store consultant name')),
                ('tt_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working timetable')),
                ('wday_hours', models.TimeField(blank=True, null=True, verbose_name='Timetable')),
                ('wend_hours', models.TimeField(blank=True, null=True, verbose_name='Timetable')),
                ('atm', models.IntegerField(blank=True, default=0, null=True, verbose_name='ATM number')),
                ('chest_frz_ru', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horizontal freezer /Russian, Mongolia/')),
                ('chest_frz_kr', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horizontal freezer /Korea/')),
                ('up_frz_kr', models.IntegerField(blank=True, default=0, null=True, verbose_name='Vertical freezer /Korea')),
                ('ba_rob_frz', models.IntegerField(blank=True, default=0, null=True, verbose_name='Baskin robbins freezer')),
                ('up_frz_suu', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horizontal milk freezer')),
                ('up_frz_ice', models.IntegerField(blank=True, null=True, verbose_name='Horizontal icemark freezer')),
                ('storabox', models.BooleanField(blank=True, null=True, verbose_name='Stora Box')),
                ('Umoney', models.BooleanField(blank=True, null=True, verbose_name='Bus card stadium or not')),
                ('alc_reason', models.TextField(blank=True, null=True, verbose_name='Reason for not having alcohol license')),
                ('ciga_reason', models.TextField(blank=True, null=True, verbose_name='Reason for not having cigar license')),
                ('reason_not_24', models.TextField(blank=True, null=True, verbose_name='Reason for not having 24 hour working')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Closing date')),
                ('close_reason', models.TextField(blank=True, null=True, verbose_name='Reason for closing store')),
                ('near_store', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of the store within 500 meters')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_consultant_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_consultant_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Store Consultant',
                'db_table': 'store_consultant',
            },
        ),
    ]
