# Generated by Django 2.1.7 on 2024-03-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='store_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Store ID'),
        ),
    ]
