# Generated by Django 2.1.7 on 2024-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0004_auto_20240304_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='tv_screen',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tv screen'),
        ),
    ]
