# Generated by Django 2.1.7 on 2024-03-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0005_storeconsultant_tv_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Consultants',
        ),
    ]
