# Generated by Django 2.1.7 on 2024-03-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0009_allocation_consultants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconsultant',
            name='prc_grade',
        ),
    ]
