# Generated by Django 2.1.7 on 2024-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0010_remove_storeconsultant_prc_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='prc_grade',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pricing policy'),
        ),
    ]
