# Generated by Django 2.1.7 on 2024-03-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0013_allocation_area_consultants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='area',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Consultants',
        ),
    ]
