# Generated by Django 2.1.7 on 2024-03-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_consultant', '0016_auto_20240318_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year')),
                ('month', models.CharField(blank=True, max_length=12, null=True, verbose_name='Month')),
                ('team_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Team No')),
                ('store_cons', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Consultant')),
                ('storeID', models.CharField(blank=True, max_length=5, null=True, verbose_name='Store ID')),
                ('store_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Allocation',
                'db_table': 'allocation',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Area No')),
                ('team_man_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area manager name')),
                ('team_man_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area manager surname')),
                ('team_man_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Area manager email address')),
                ('team_man_phone', models.IntegerField(blank=True, default=0, null=True, verbose_name='Area manager phone number')),
                ('team_man_sex', models.BooleanField(blank=True, null=True, verbose_name='Area manager gender')),
                ('team_man_birthdt', models.DateField(blank=True, null=True, verbose_name='Area manager birthday')),
                ('team_man_rel_status', models.BooleanField(blank=True, null=True, verbose_name='Area manager marital status')),
                ('team_man_child', models.IntegerField(blank=True, default=0, null=True, verbose_name='Area manager number of children')),
                ('team_man_Addr1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living city')),
                ('team_man_Addr2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living district')),
                ('team_man_Addr3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living khoroo')),
                ('team_man_Addr4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address detail')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_manager_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_manager_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Area Manger',
                'db_table': 'area_manager',
            },
        ),
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store name of consultants')),
                ('sc_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Surname of store consultants')),
                ('sc_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address of store consultants')),
                ('sc_phone', models.IntegerField(blank=True, null=True, verbose_name='Phone number of store consultants')),
                ('sc_sex', models.BooleanField(blank=True, null=True, verbose_name='Gender of store consultant')),
                ('sc_birthdt', models.DateField(blank=True, null=True, verbose_name='Birth date of store consultant')),
                ('sc_rel_status', models.BooleanField(blank=True, null=True, verbose_name='Relation status of store consultant')),
                ('sc_child', models.IntegerField(blank=True, null=True, verbose_name='Child number of store consultant')),
                ('sc_Addr1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living city')),
                ('sc_Addr2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living district')),
                ('sc_Addr3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living khoroo')),
                ('sc_Addr4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detail address')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sc_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sc_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Consultant',
                'db_table': 'consultant',
            },
        ),
    ]
