# Generated by Django 2.1.7 on 2024-03-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0017_allocation_area_consultants'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_consultant.Area'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_consultant.Consultants'),
        ),
    ]
