# Generated by Django 2.1.7 on 2024-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0019_auto_20240322_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
    ]
