# Generated by Django 2.1.7 on 2024-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0020_auto_20240325_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date'),
        ),
    ]
