# Generated by Django 2.1.7 on 2024-03-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0022_auto_20240325_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconsultant',
            name='am_num',
        ),
        migrations.RemoveField(
            model_name='storeconsultant',
            name='sm_num',
        ),
        migrations.RemoveField(
            model_name='storeconsultant',
            name='tv_screen',
        ),
    ]
