# Generated by Django 2.1.7 on 2024-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0024_auto_20240325_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='wday_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Timetable'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='wend_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Timetable'),
        ),
    ]
