# Generated by Django 2.1.7 on 2024-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0025_auto_20240326_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='prc_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pricing policy'),
        ),
    ]
