# Generated by Django 2.1.7 on 2024-04-28 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0026_auto_20240423_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_consultant_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_consultant_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='sm_phone',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Store manager phone'),
        ),
    ]
