# Generated by Django 2.1.7 on 2024-05-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0027_auto_20240428_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='lunch_case_L8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Хоолны хөргүүрийн тоо '),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='walkin_chiller',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Уух ус ундааны босоо хөргүүрийн хаалганы тоо'),
        ),
    ]
