# Generated by Django 2.1.7 on 2024-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0028_auto_20240520_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
