# Generated by Django 2.1.7 on 2024-06-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0029_allocation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='tags',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
