# Generated by Django 2.1.7 on 2024-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0030_auto_20240612_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
