# Generated by Django 2.1.7 on 2024-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0033_allocation_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='store',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='tags',
        ),
        migrations.AddField(
            model_name='allocation',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
