# Generated by Django 2.1.7 on 2024-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0034_auto_20240617_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='tags',
        ),
        migrations.AddField(
            model_name='allocation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store_consultant.Tag'),
        ),
    ]
