# Generated by Django 2.1.7 on 2024-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0035_auto_20240624_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='current_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
