# Generated by Django 2.1.7 on 2024-07-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0036_storeconsultant_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconsultant',
            name='current_status',
        ),
    ]
