# Generated by Django 2.1.7 on 2024-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0037_remove_storeconsultant_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='alc_lic_yn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Архины зөвшөөрөлтэй эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='alc_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Архины зөвшөөрөлтэй бол сул, эсвэл чанга аль нь вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='building_purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дэлгүүр байршдаг барилга ямар зориулалттай вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='bus_station_range',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Автобусны буудлын зай'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='car_park_slot',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Машины зогсоолтой бол хичнээн машин багтах боломжтой вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='chair_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Суух хэсэгтэй бол хэдэн сандал байгаа вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='cu_bar',
            field=models.BooleanField(blank=True, null=True, verbose_name='CU BAR-тай эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='cu_bar_door',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CU BAR тоо /Хаалга/'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='customer_base',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Объектийн ажилтан, оршин суугчийн тоо'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='desk_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Суух хэсэгтэй бол хэдэн ширээ байгаа вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='doorstep_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Гадна шатны тоо'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='doorstep_yn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дэлгүүрийн үүд шаттай эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='entrace_connection',
            field=models.BooleanField(blank=True, null=True, verbose_name='Орцруу холбогддог эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='entrace_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дэлгүүр хэдэн орж гарах гарц/үүд-тэй вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='garbage_area',
            field=models.BooleanField(blank=True, null=True, verbose_name='Тусдаа хогийн цэгтэй эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='garbage_transport',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Хогоо сардаа хэд ачуулдаг вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='high_school_range',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Урсгалд нөлөөлдөг дунд сургуультай эсэх, зай?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='in_out_flow',
            field=models.BooleanField(blank=True, null=True, verbose_name='Хотоос гарах урсгалын салбар бол аль талд нь байрлалтай вэ?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='near_bus_station',
            field=models.BooleanField(blank=True, null=True, verbose_name='Автобусны буудалтай ойр байршдаг уу?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='out_banner_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Гадна хаягны тоо'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='out_city_flow',
            field=models.BooleanField(blank=True, null=True, verbose_name='Хотоос гарах урсгал эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='shelf',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дэлгүүрийн лагууны тоо'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='shelf_list',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дэлгүүрийн тавцангийн тоо'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='squat_toilet_yn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дэлгүүрийн гадна модон 00 той эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='sub_rent1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дамжуулдаг түрээсэлдэг төрөл'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='sub_rent2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дамжуулдаг түрээсэлдэг төрөл'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='tobbacco_yn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Утаат тамхины зөвшөөрөлтэй эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='toilet_seat',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Суултуурын тоо'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='university_range',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Урсгалд нөлөөлдөг их суруультай эсэх, зай?'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='vape_sell',
            field=models.BooleanField(blank=True, null=True, verbose_name='Электрон тамхи зарж буй эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='war_yn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Дэлгүүр агуулахтай эсэх'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='water_tank',
            field=models.BooleanField(blank=True, null=True, verbose_name='Зөөврийн устай эсэх'),
        ),
    ]
