# Generated by Django 2.1.7 on 2024-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0038_auto_20240903_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='use_yn',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Use yn'),
        ),
    ]
