# Generated by Django 2.1.7 on 2024-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0039_storeconsultant_use_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='sub_rent1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дамжуулдаг түрээсэлдэг төрөл'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='sub_rent2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дамжуулдаг түрээсэлдэг төрөл'),
        ),
    ]
