# Generated by Django 2.1.7 on 2024-10-22 17:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0040_auto_20241007_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='tags',
        ),
        migrations.AddField(
            model_name='allocation',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Tags and Store IDs'),
        ),
    ]
