# Generated by Django 2.1.7 on 2024-10-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0042_auto_20241022_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='tags',
        ),
        migrations.AddField(
            model_name='allocation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store_consultant.Tag'),
        ),
    ]
