# Generated by Django 2.1.7 on 2024-10-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0043_auto_20241023_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='tags',
        ),
    ]
