# Generated by Django 2.1.7 on 2024-10-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0044_remove_allocation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags and Store IDs'),
        ),
    ]
