# Generated by Django 2.1.7 on 2024-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0045_allocation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='consultants',
            field=models.ManyToManyField(related_name='tags', to='store_consultant.Consultants'),
        ),
    ]
