# Generated by Django 2.1.7 on 2024-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0047_sc_store_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_store_allocation',
            name='sc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
