# Generated by Django 2.1.7 on 2024-10-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0048_sc_store_allocation_sc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_store_allocation',
            name='store_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
