# Generated by Django 2.1.7 on 2024-11-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0049_sc_store_allocation_store_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='area',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consultants',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sc_store_allocation',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='sc_store_allocation',
            name='store',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='consultants',
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.DeleteModel(
            name='Consultants',
        ),
        migrations.DeleteModel(
            name='SC_Store_Allocation',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
