# Generated by Django 2.1.7 on 2024-11-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_consultant', '0050_auto_20241104_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year')),
                ('month', models.CharField(blank=True, max_length=12, null=True, verbose_name='Month')),
                ('team_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Team No')),
                ('store_cons', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Consultant')),
                ('storeID', models.CharField(blank=True, max_length=5, null=True, verbose_name='Store ID')),
                ('store_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Name')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags and Store IDs')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_consultant.Area')),
            ],
            options={
                'verbose_name': 'Allocation',
                'db_table': 'allocation',
            },
        ),
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store name of consultants')),
                ('sc_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Surname of store consultants')),
                ('sc_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address of store consultants')),
                ('sc_phone', models.IntegerField(blank=True, null=True, verbose_name='Phone number of store consultants')),
                ('sc_sex', models.BooleanField(blank=True, null=True, verbose_name='Gender of store consultant')),
                ('sc_birthdt', models.DateField(blank=True, null=True, verbose_name='Birth date of store consultant')),
                ('sc_rel_status', models.BooleanField(blank=True, null=True, verbose_name='Relation status of store consultant')),
                ('sc_child', models.IntegerField(blank=True, null=True, verbose_name='Child number of store consultant')),
                ('sc_Addr1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living city')),
                ('sc_Addr2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living district')),
                ('sc_Addr3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Living khoroo')),
                ('sc_Addr4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detail address')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sc_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sc_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Consultant',
                'db_table': 'consultant',
            },
        ),
        migrations.CreateModel(
            name='SC_Store_Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('sc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_no', models.CharField(blank=True, max_length=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_allocations', to='store_consultant.Consultants')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_allocations', to='store_consultant.StoreConsultant')),
            ],
            options={
                'verbose_name': 'SC Store Allocation',
                'verbose_name_plural': 'SC Store Allocations',
                'db_table': 'sc_store_allocation',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consultants', models.ManyToManyField(related_name='tags', to='store_consultant.Consultants')),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_consultant.Consultants'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
