# Generated by Django 2.1.7 on 2024-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0051_auto_20241104_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='in_out_flow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Хотоос гарах урсгалын салбар бол аль талд нь байрлалтай вэ?'),
        ),
    ]
