# Generated by Django 2.1.5 on 2019-02-13 22:34

import cupp.point.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(choices=[('MNP', 'Mom-n-pop store'), ('Cafe', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur')], max_length=10, verbose_name='Type')),
                ('lat', models.CharField(default='47.9116', max_length=50, verbose_name='Latitude')),
                ('lon', models.CharField(default='106.9057', max_length=50, verbose_name='Longitude')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, null=True, verbose_name='Location grade')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Size')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landlord name')),
                ('owner_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landlord phone')),
                ('owner_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landlord email')),
                ('base_rent_rate', models.IntegerField(blank=True, null=True, verbose_name='Base rent rate')),
                ('expected_rent_rate', models.IntegerField(blank=True, null=True, verbose_name='Expected rent rate')),
                ('proposed_layout', models.FileField(blank=True, null=True, upload_to=cupp.point.models.upload_file, verbose_name='Proposed layout')),
                ('availability', models.BooleanField(blank=True, null=True, verbose_name='Availability')),
                ('available_date', models.DateTimeField(blank=True, null=True, verbose_name='Available date')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('bep', models.IntegerField(blank=True, null=True, verbose_name='Breakeven point')),
                ('expected_sales', models.IntegerField(blank=True, null=True, verbose_name='Expected daily sales')),
                ('passers', models.IntegerField(blank=True, null=True, verbose_name='Average passers an hour')),
                ('hh', models.IntegerField(blank=True, null=True, verbose_name='Households in the direct area')),
                ('office', models.IntegerField(blank=True, null=True, verbose_name='Office people in the direct area')),
                ('students', models.IntegerField(blank=True, null=True, verbose_name='School/University students in the direct area')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Creadted by')),
            ],
            options={
                'verbose_name': 'Цэг',
                'db_table': 'cupp_point',
            },
        ),
        migrations.CreateModel(
            name='PointPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=cupp.point.models.upload_file)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='point.Point')),
            ],
            options={
                'verbose_name': 'Цэгийн зураг',
                'db_table': 'cupp_point_photo',
            },
        ),
    ]
