# Generated by Django 2.1.7 on 2019-02-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lat', models.CharField(default='47.9116', max_length=50, verbose_name='Latitude')),
                ('lon', models.CharField(default='106.9057', max_length=50, verbose_name='Longitude')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cks', to='point.Point')),
            ],
            options={
                'verbose_name': 'Бусад цэг',
                'db_table': 'cupp_point_ck',
            },
        ),
    ]
