# Generated by Django 2.1.7 on 2019-02-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_circlek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlek',
            name='point',
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('PP', 'Potential Point'), ('CU', 'CU'), ('MNP', 'Mom-n-pop store'), ('Cafe', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur')], max_length=10, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='CircleK',
        ),
    ]
