# Generated by Django 2.1.7 on 2019-02-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_auto_20190217_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='name',
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('PP', 'Potential Point'), ('CU', 'CU Store'), ('MNP', 'Mom-n-pop Store'), ('Cafe', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur')], max_length=10, verbose_name='Type'),
        ),
    ]
