# Generated by Django 2.1.7 on 2019-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_auto_20190218_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='available_date',
            field=models.DateField(blank=True, null=True, verbose_name='Available date'),
        ),
    ]
