# Generated by Django 2.1.7 on 2019-02-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0006_auto_20190219_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='available_date',
        ),
    ]
