# Generated by Django 2.1.7 on 2019-02-21 00:08

import cupp.point.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0008_point_available_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='expected_rent_rate',
        ),
        migrations.AddField(
            model_name='point',
            name='isr_file',
            field=models.FileField(blank=True, null=True, upload_to=cupp.point.models.upload_file, verbose_name='ISR excel file'),
        ),
        migrations.AddField(
            model_name='point',
            name='max_rent_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum rent'),
        ),
        migrations.AddField(
            model_name='point',
            name='pl_file',
            field=models.FileField(blank=True, null=True, upload_to=cupp.point.models.upload_file, verbose_name='P&L excel file'),
        ),
        migrations.AddField(
            model_name='point',
            name='radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radius by meter /limit 1km/'),
        ),
        migrations.AddField(
            model_name='point',
            name='turnover_rent_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Turnover rent percentage'),
        ),
    ]
