# Generated by Django 2.1.7 on 2019-02-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0009_auto_20190221_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='base_rent_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Base rent rate'),
        ),
        migrations.AlterField(
            model_name='point',
            name='max_rent_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Maximum rent'),
        ),
        migrations.AlterField(
            model_name='point',
            name='radius',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Radius by meter /limit 1km/'),
        ),
        migrations.AlterField(
            model_name='point',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='point',
            name='turnover_rent_percent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Turnover rent percentage'),
        ),
    ]
