# Generated by Django 2.1.7 on 2019-02-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0010_auto_20190225_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10, null=True, verbose_name='Location grade'),
        ),
    ]
