# Generated by Django 2.1.7 on 2019-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0011_auto_20190225_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='base_rent_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Base rent'),
        ),
    ]
