# Generated by Django 2.1.7 on 2019-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0012_auto_20190225_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Address'),
        ),
    ]
