# Generated by Django 2.1.7 on 2019-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0014_auto_20190227_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Point'},
        ),
        migrations.AlterModelOptions(
            name='pointphoto',
            options={'verbose_name': 'Point Photo'},
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('PP', 'Potential Point'), ('CU', 'CU Store'), ('MNP', 'Mom-n-pop Store'), ('CA', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur')], max_length=10, verbose_name='Type'),
        ),
    ]
