# Generated by Django 2.1.7 on 2023-12-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0017_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(default='', max_length=50, unique=True, verbose_name='District and sum name')),
            ],
            options={
                'verbose_name': 'District',
                'db_table': 'cupp_district',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='sum_name',
        ),
        migrations.AddField(
            model_name='city',
            name='city_code',
            field=models.IntegerField(default=0, null=True, verbose_name='City and aimag code'),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='point.City'),
        ),
    ]
