# Generated by Django 2.1.7 on 2023-12-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0018_auto_20231225_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='addr1_prov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='point.City', verbose_name='City and Aimag'),
        ),
        migrations.AddField(
            model_name='point',
            name='addr2_dist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='point.District', verbose_name='District and Sum'),
        ),
        migrations.AddField(
            model_name='point',
            name='address_det',
            field=models.CharField(default='', max_length=500, verbose_name='Address detail'),
        ),
        migrations.AddField(
            model_name='point',
            name='adv',
            field=models.CharField(default='', max_length=100, verbose_name='Advantage'),
        ),
        migrations.AddField(
            model_name='point',
            name='cont_ed_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Rent agreement end date'),
        ),
        migrations.AddField(
            model_name='point',
            name='cont_st_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Rent agreement start date'),
        ),
        migrations.AddField(
            model_name='point',
            name='disadv',
            field=models.CharField(default='', max_length=100, verbose_name='Disadvantage'),
        ),
        migrations.AddField(
            model_name='point',
            name='floor',
            field=models.IntegerField(blank=True, default=0, verbose_name='Floor number'),
        ),
        migrations.AddField(
            model_name='point',
            name='near_gs_cvs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='GS25 number'),
        ),
        migrations.AddField(
            model_name='point',
            name='near_school',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='School number'),
        ),
        migrations.AddField(
            model_name='point',
            name='park_slot',
            field=models.IntegerField(blank=True, default=0, verbose_name='Park number'),
        ),
        migrations.AddField(
            model_name='point',
            name='propose',
            field=models.CharField(default='', max_length=100, verbose_name='Suggestions for improvement'),
        ),
        migrations.AddField(
            model_name='point',
            name='rent_near',
            field=models.CharField(default='', max_length=50, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='point',
            name='rent_tp',
            field=models.BooleanField(blank=True, null=True, verbose_name='Type of rent agreement'),
        ),
        migrations.AddField(
            model_name='point',
            name='sp_name',
            field=models.CharField(default='', max_length=50, verbose_name='SP name'),
        ),
        migrations.AddField(
            model_name='point',
            name='zip_code',
            field=models.CharField(default='', max_length=100, verbose_name='Zip code'),
        ),
    ]
