# Generated by Django 2.1.7 on 2024-02-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0018_auto_20231225_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=50, unique=True, verbose_name='Type name')),
                ('type_cd', models.CharField(default='', max_length=50, unique=True, verbose_name='Type code')),
                ('icon', models.FileField(upload_to='images/ui')),
            ],
            options={
                'verbose_name': 'Type',
                'db_table': 'cupp_type',
            },
        ),
        migrations.AddField(
            model_name='point',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='point',
            name='store_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Store ID'),
        ),
        migrations.AddField(
            model_name='point',
            name='store_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('PP', 'Potential Point'), ('CU', 'CU Store'), ('MNP', 'Mom-n-pop Store'), ('CA', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur'), ('DG', 'Daily Grocers'), ('FM', 'Fresco Supermarket'), ('GP', 'GOODPRICE'), ('MM', 'M mart'), ('NA', 'Naran Supermarket'), ('SS', 'Sansar Supermarket'), ('TC', 'Ta Chi mart'), ('GS', 'GS25')], max_length=10, verbose_name='Type'),
        ),
    ]
