# Generated by Django 2.1.7 on 2024-01-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0020_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type'},
        ),
    ]
