# Generated by Django 2.1.7 on 2024-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0021_auto_20240109_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to='ui/'),
        ),
    ]
