# Generated by Django 2.1.7 on 2024-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0024_auto_20240112_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to='../static/images/ui/'),
        ),
    ]
