# Generated by Django 2.1.7 on 2024-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0025_auto_20240112_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.FileField(blank=True, upload_to='temp/'),
        ),
    ]
