# Generated by Django 2.1.7 on 2024-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0026_auto_20240112_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='address_det',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Address detail'),
        ),
        migrations.AlterField(
            model_name='point',
            name='adv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Advantage'),
        ),
        migrations.AlterField(
            model_name='point',
            name='disadv',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Disadvantage'),
        ),
        migrations.AlterField(
            model_name='point',
            name='propose',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Suggestions for improvement'),
        ),
        migrations.AlterField(
            model_name='point',
            name='rent_near',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='point',
            name='sp_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SP name'),
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('PP', 'Potential Point'), ('CU', 'CU Store'), ('MNP', 'Mom-n-pop Store'), ('CA', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur'), ('DG', 'Daily Grocers'), ('FM', 'Fresco Supermarket'), ('GP', 'GOODPRICE'), ('MM', 'M mart'), ('NA', 'Naran Supermarket'), ('SS', 'Sansar Supermarket'), ('TC', 'Ta Chi mart'), ('GS', 'GS25')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='point',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Zip code'),
        ),
    ]
