# Generated by Django 2.1.7 on 2024-01-22 15:24

import cupp.point.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0027_auto_20240112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to=cupp.point.models.icon_file),
        ),
    ]
