# Generated by Django 2.1.7 on 2024-01-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0030_auto_20240122_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to='../static/images/ui/'),
        ),
    ]
