# Generated by Django 2.1.7 on 2024-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0032_auto_20240122_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
