# Generated by Django 2.1.7 on 2024-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0034_auto_20240122_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.FileField(blank=True, upload_to='temp/'),
        ),
    ]
