# Generated by Django 2.1.7 on 2024-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0037_auto_20240123_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
    ]
