# Generated by Django 2.1.7 on 2024-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0039_auto_20240123_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('GS', 'GS25'), ('CU', 'CU'), ('PP', 'Potential Point'), ('MNP', 'Mom-n-pop Store'), ('CA', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur'), ('TC', 'Ta Chi mart'), ('SS', 'Sansar Supermarket'), ('NA', 'Naran Supermarket'), ('MM', 'M mart'), ('GP', 'GOODPRICE'), ('FM', 'Fresco Supermarket'), ('DG', 'Daily Grocers')], max_length=10, verbose_name='Type'),
        ),
    ]
