# Generated by Django 2.1.7 on 2024-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0040_auto_20240123_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('PP', 'Potential Point'), ('CU', 'CU Store'), ('MNP', 'Mom-n-pop Store'), ('CA', 'Cafe'), ('CK', 'Circle K'), ('EE', 'Eco Express'), ('NS', 'Nomin Supermarket'), ('VP', 'Vpoint'), ('EM', 'Emart'), ('OS', 'Orgil Supermarket'), ('MD', 'Minii Delguur'), ('DG', 'Daily Grocers'), ('FM', 'Fresco Supermarket'), ('GP', 'GOODPRICE'), ('MM', 'M mart'), ('NA', 'Naran Supermarket'), ('SS', 'Sansar Supermarket'), ('TC', 'Ta Chi mart'), ('GS', 'GS25')], max_length=10, verbose_name='Type'),
        ),
    ]
