# Generated by Django 2.1.7 on 2024-02-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0019_auto_20240208_0957'),
        ('point', '0041_auto_20240124_1407'),
    ]

    operations = [
    ]
