# Generated by Django 2.1.7 on 2024-02-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0042_merge_20240208_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='addr1_prov',
        ),
        migrations.RemoveField(
            model_name='point',
            name='addr2_dist',
        ),
        migrations.RemoveField(
            model_name='point',
            name='address_det',
        ),
        migrations.RemoveField(
            model_name='point',
            name='adv',
        ),
        migrations.RemoveField(
            model_name='point',
            name='cont_ed_dt',
        ),
        migrations.RemoveField(
            model_name='point',
            name='cont_st_dt',
        ),
        migrations.RemoveField(
            model_name='point',
            name='disadv',
        ),
        migrations.RemoveField(
            model_name='point',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='point',
            name='near_gs_cvs',
        ),
        migrations.RemoveField(
            model_name='point',
            name='near_school',
        ),
        migrations.RemoveField(
            model_name='point',
            name='park_slot',
        ),
        migrations.RemoveField(
            model_name='point',
            name='propose',
        ),
        migrations.RemoveField(
            model_name='point',
            name='rent_near',
        ),
        migrations.RemoveField(
            model_name='point',
            name='rent_tp',
        ),
        migrations.RemoveField(
            model_name='point',
            name='sp_name',
        ),
        migrations.RemoveField(
            model_name='point',
            name='zip_code',
        ),
    ]
