# Generated by Django 2.1.7 on 2024-02-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0043_auto_20240208_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='point',
            name='store_name',
        ),
    ]
