# Generated by Django 2.1.7 on 2024-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0044_auto_20240223_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='store_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Store ID'),
        ),
        migrations.AddField(
            model_name='point',
            name='store_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Store name'),
        ),
    ]
