# Generated by Django 2.1.7 on 2024-02-23 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0046_remove_point_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
