# Generated by Django 2.1.7 on 2024-02-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0047_point_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='modified_by',
        ),
    ]
