# Generated by Django 2.1.7 on 2024-02-27 14:08

import cupp.point.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0050_auto_20240227_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to=cupp.point.models.icon_file),
        ),
    ]
