# Generated by Django 2.1.7 on 2024-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0051_auto_20240227_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to='static/images/ui/'),
        ),
    ]
