# Generated by Django 2.1.7 on 2024-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0052_auto_20240227_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.FileField(upload_to='images/ui'),
        ),
    ]
