# Generated by Django 2.1.7 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0055_storeplanning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplanning',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Store ID'),
        ),
    ]
