# Generated by Django 2.1.7 on 2024-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0056_auto_20240304_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Store ID'),
        ),
    ]
