# Generated by Django 2.1.7 on 2024-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0058_auto_20240318_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeplanning',
            name='addr3_khr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Хороо'),
        ),
        migrations.AddField(
            model_name='storeplanning',
            name='lessee_promise',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Амлалт'),
        ),
    ]
