# Generated by Django 2.1.7 on 2024-04-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0059_auto_20240322_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeplanning',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_plannings', to='point.Point'),
        ),
    ]
