# Generated by Django 2.1.7 on 2024-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0060_storeplanning_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplanning',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Store ID'),
        ),
    ]
