# Generated by Django 2.1.7 on 2024-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0061_auto_20240404_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplanning',
            name='adv',
            field=models.TextField(blank=True, default='', verbose_name='Advantage'),
        ),
        migrations.AlterField(
            model_name='storeplanning',
            name='disadv',
            field=models.TextField(blank=True, default='', verbose_name='Disadvantage'),
        ),
    ]
