# Generated by Django 2.1.7 on 2024-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0063_auto_20240415_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeplanning',
            name='address_simple',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Simple'),
        ),
    ]
