# Generated by Django 2.1.7 on 2024-01-24 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCategory',
            fields=[
                ('activ_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('activ_cat', models.CharField(max_length=255)),
                ('activ_desc', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_action_categories', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_action_categories', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Action Category',
                'db_table': 'action_category',
            },
        ),
        migrations.CreateModel(
            name='ActionOwner',
            fields=[
                ('own_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('own_pos', models.CharField(max_length=255)),
                ('own_dep', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_action_owners', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_action_owners', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Action owners',
                'db_table': 'action_owners',
            },
        ),
        migrations.CreateModel(
            name='StoreDailyLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('store_no', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=255)),
                ('activ_desc', models.TextField()),
                ('resp_action', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('action_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ActionOwner')),
                ('activ_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ActionCategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_store_daily_logs', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_store_daily_logs', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Store Daily Logs',
                'db_table': 'store_daily_log',
            },
        ),
    ]
