# Generated by Django 2.1.7 on 2024-01-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncategory',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='actionowner',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='storedailylog',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='actioncategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_categories', to=settings.AUTH_USER_MODEL, verbose_name='Creadted by'),
        ),
        migrations.AlterField(
            model_name='actionowner',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_owners', to=settings.AUTH_USER_MODEL, verbose_name='Creadted by'),
        ),
        migrations.AlterField(
            model_name='storedailylog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_daily_logs', to=settings.AUTH_USER_MODEL, verbose_name='Creadted by'),
        ),
    ]
