# Generated by Django 2.1.7 on 2024-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20240125_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedailylog',
            name='resp_action',
            field=models.TextField(null=True),
        ),
    ]
