# Generated by Django 2.1.7 on 2024-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20240126_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedailylog',
            name='resp_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
