# Generated by Django 2.1.7 on 2024-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_storedailylog_consequences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actioncategory',
            options={'verbose_name': 'Action Categorie'},
        ),
        migrations.AlterModelOptions(
            name='actionowner',
            options={'verbose_name': 'Action owner'},
        ),
        migrations.AlterModelOptions(
            name='storedailylog',
            options={'verbose_name': 'Store Daily Log'},
        ),
    ]
