# Generated by Django 2.1.7 on 2024-02-07 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Store id')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Area size')),
                ('sitting_size', models.FloatField(blank=True, default=0, null=True, verbose_name='Sitting area size')),
                ('war_size', models.FloatField(blank=True, default=0, null=True, verbose_name='Warehouse size')),
                ('toiler_size', models.FloatField(blank=True, default=0, null=True, verbose_name='Toilet size')),
                ('resale_size', models.FloatField(blank=True, default=0, null=True, verbose_name='Hall size')),
                ('shelf', models.IntegerField(blank=True, default=0, null=True, verbose_name='Shelf number')),
                ('wall_shelf', models.IntegerField(blank=True, default=0, null=True, verbose_name='Wall shelf numver')),
                ('cash_shelf', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cash shelf number')),
                ('st_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store trainer name')),
                ('chair_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='Chair number')),
                ('desk_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='Desk number')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Date of plan')),
                ('displayed_date', models.DateField(blank=True, null=True, verbose_name='Displayed date')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='Opening date')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Opening time')),
                ('light_box', models.IntegerField(blank=True, default=0, null=True, verbose_name='Light board number')),
                ('sand_grill', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sandwich grill number')),
                ('slushie_mach', models.IntegerField(blank=True, default=0, null=True, verbose_name='Slushie machine number')),
                ('icecream_mach', models.IntegerField(blank=True, default=0, null=True, verbose_name='Icecream machine')),
                ('mcs_mach', models.IntegerField(blank=True, default=0, null=True, verbose_name='MCS machine')),
                ('disp_5_mach', models.IntegerField(blank=True, default=0, null=True, verbose_name='Zuv aarts machine 5')),
                ('disp_3_mach', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tea machine 3')),
                ('horizontal_freeze', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horizontal freezer')),
                ('coffee_mach_button', models.IntegerField(blank=True, default=0, null=True, verbose_name='Coffee machine number')),
                ('coffee_mach_led', models.IntegerField(blank=True, default=0, null=True, verbose_name='Coffee machine led screen')),
                ('steamer', models.IntegerField(blank=True, default=0, null=True, verbose_name='Steamer number')),
                ('can_warmer', models.IntegerField(blank=True, default=0, null=True, verbose_name='Coffee warmer number')),
                ('food_warmer', models.IntegerField(blank=True, default=0, null=True, verbose_name='Food warmer number')),
                ('vertical_freezer', models.IntegerField(blank=True, default=0, null=True, verbose_name='ISF vertical freezer')),
                ('dogbuggi_cooker', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tteok-bokki machine number')),
                ('hot_water_disp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Water boiler number')),
                ('tv_screen', models.IntegerField(blank=True, default=0, null=True, verbose_name='TV number')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_trainer_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_trainer_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Store Trainer',
                'db_table': 'store_trainer',
            },
        ),
    ]
