# Generated by Django 2.1.7 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_trainer', '0002_auto_20240301_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetrainer',
            name='store_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='storetrainer',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Store ID'),
        ),
    ]
