# Generated by Django 2.1.7 on 2024-03-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_trainer', '0004_auto_20240305_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetrainer',
            old_name='toiler_size',
            new_name='toilet_size',
        ),
    ]
