# Generated by Django 2.1.7 on 2024-01-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_auto_20240118_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensiontablelicenseprovider',
            name='lic_id',
        ),
        migrations.RemoveField(
            model_name='maintable',
            name='lic_id',
        ),
        migrations.DeleteModel(
            name='DimensionTable',
        ),
        migrations.DeleteModel(
            name='DimensionTableLicenseProvider',
        ),
        migrations.DeleteModel(
            name='MainTable',
        ),
    ]
