# Generated by Django 2.1.7 on 2024-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_auto_20240123_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='alc_closetime',
            field=models.TimeField(null=True, verbose_name='Time to sell out alchohol'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='alc_opentime',
            field=models.TimeField(null=True, verbose_name='Time to start selling alcohol'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='camera_cnt',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total number of cameras'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='lic_sqrm',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Licensed area'),
        ),
    ]
