# Generated by Django 2.1.7 on 2024-02-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20240130_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensiontablelicenseprovider',
            options={'verbose_name': 'Dimenstion Table License Provider'},
        ),
    ]
