# Generated by Django 2.1.7 on 2024-02-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_auto_20240215_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='lic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='license.DimensionTable', verbose_name='License type'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_id_nm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Type Name'),
        ),
    ]
