# Generated by Django 2.1.7 on 2024-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_remove_maintable_lic_id_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='lic_id_nm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Type Name'),
        ),
    ]
