# Generated by Django 2.1.7 on 2024-02-15 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_maintable_lic_id_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='alc_closetime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time to sell out alchohol'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='alc_opentime',
            field=models.TimeField(blank=True, null=True, verbose_name='Time to start selling alcohol'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Licensed Employee'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_prov_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Provider ID'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_prov_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Provider Name'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_sqrm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Licensed area'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='store_id',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Store number must be a 5-digit number')]),
        ),
    ]
