# Generated by Django 2.1.7 on 2024-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_auto_20240221_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='camera_cnt',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total number of cameras'),
        ),
    ]
