# Generated by Django 2.1.7 on 2024-02-22 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0015_auto_20240221_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='lic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license.DimensionTable', verbose_name='License type'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_id_nm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License Type Name'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='lic_yn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Type of rent agreement'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Store number must be a 5-digit number')]),
        ),
    ]
