# Generated by Django 2.1.7 on 2024-02-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0016_auto_20240222_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date'),
        ),
    ]
