# Generated by Django 2.1.7 on 2024-02-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0019_auto_20240226_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_modified', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
