# Generated by Django 2.1.7 on 2024-02-26 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0020_auto_20240226_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
