# Generated by Django 2.1.7 on 2024-03-27 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0025_auto_20240327_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='str_license_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
