# Generated by Django 2.1.7 on 2024-09-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0064_storeplanning_address_simple'),
        ('license', '0026_auto_20240327_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='alc_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Type of Alcohol'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='point.District', verbose_name='Licensed District'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='lic_duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Duration of License'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='lic_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='License Status'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='lic_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Type of License'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='link_path',
            field=models.URLField(blank=True, null=True, verbose_name='Link to License Document'),
        ),
    ]
