# Generated by Django 2.1.7 on 2024-10-07 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0029_disputetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputetable',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disputetable',
            name='store_no',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Store number must be a 5-digit number')], verbose_name='Үйл явдал болсон дэлгүүрийн дугаар'),
        ),
    ]
