# Generated by Django 2.1.7 on 2024-10-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0030_auto_20241007_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputetable',
            name='disp_result',
            field=models.BooleanField(blank=True, null=True, verbose_name='Хэрэг шийдэгдсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='disputetable',
            name='disp_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Хэргийн төлөв'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='ed_dt',
            field=models.DateField(blank=True, null=True, verbose_name='License Ended Date'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='st_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Rent agreement start date'),
        ),
    ]
